### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [saurvs/CBOR.jl#1]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.   This affects at least:

https://github.com/saurvs/CBOR.jl/blob/2658d364f8cfc912b62d39be0c3744c67504a721/src/encoding-common.jl#L77-L80

**Comment by saurvs** [comment]
Fixed by https://github.com/saurvs/CBOR.jl/pull/5
