### ISSUE TITLE
hex2num is deprecated

### ISSUE THREAD

**Issue by stevengj** [saurvs/CBOR.jl#7]
`hex2num` and `num2hex` are now deprecated (https://github.com/JuliaLang/julia/pull/22088).

You currently use these functions, but as I mentioned in another issue (https://github.com/JuliaLang/julia/issues/22031#issuecomment-303817621), you would be much better off using `reinterpret` anyway.

**Comment by chakravala** [comment]
alright, I was planning to create another pull request to make this package compatible with 0.7, when I do that I may look into this issue as well.

**Comment by chakravala** [comment]
This change has now been implemented in the new pull request #8 for Julia 0.7+ and 1.1+

however, the tests are not passing yet, there seems to be some numerical error
